[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "plugin-spectrum-processor"
version = "0.2.1"
description = "Atom plugin to process spectrum."
readme = "README.md"
keywords = [
    "spectroscopy",
    "atomic emission spectroscopy",
    "linear detector",
]
authors = [
    {name = "Pavel Vaschenko", email="vaschenko@vmk.ru"},
]
maintainers = [
    {name = "Pavel Vaschenko", email="vaschenko@vmk.ru"},
]
license = {text = "MIT License"}
dependencies = [
    "setuptools>=75.6.0",
    "spectrumlab>=0.9.2",
]
requires-python = ">=3.12"

[dependency-groups]
linting = [
]
testing = [
    "pytest",
    "pytest-cov",
    "spectrumlab_emulations",
    "spectrumlab_spectral_line>=0.1.0",
]
notebooks = [
    "ipympl>=0.10.0",
    "jupyter>=1.1.1",
]
dev = [
    {include-group = "linting"},
    {include-group = "testing"},
    {include-group = "notebooks"},
]
notebook = [
    "ipympl>=0.10.0",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*.csv", "*.md", "*.txt", "*.xml"]

[tool.uv.sources]
spectrumlab = { git = "https://github.com/Exinker/spectrumlab" }
spectrumlab_spectral_line = { git = "https://github.com/Exinker/spectrumlab-spectral-line" }

spectrumlab_emulations = { path = "C:/Users/Exinker/Documents/spectrumlab-emulations", editable = true }
